name: Invoke Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  invoke:
    # استدعاء الملف المشترك الموجود في نفس المستودع
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      build-command: "python setup.py build"
